### ISSUE TITLE
QBJ filename inconsistency

### ISSUE THREAD

**Issue by geoffrey-wu** [JemCasey/buzzpoint-migrator#1]
An issue I ran into when running this for Penn Bowl is that there seems to be an inconsistency with how the README recommends that the qbj files are named and how they are actually parsed for the round number:

> Then, in each tournament folder, add a folder called game_files and insert the qbj files. Each files name should start with the round number then an underscore, e.g. 1_Team_One_Team_Two.qbj

https://github.com/JemCasey/buzzpoint-migrator/blob/758c98056333f03fef8292b07df2ecb3404158ab/migrate-tournaments.js#L86

It seems that the code only works if the tournament is PACE; otherwise, the README wants the first thing in the filename to be the round number but the code needs it to be the second thing (after the string "Round_" or smth).

**Comment by JemCasey** [comment]
thanks Geoffrey. I noticed that recently but forgot to fix the readme (as you surmised, Round_* is the expected format)--it's updated now.
